name: Get Citation Data

on: 
 page_build: 
 schedule:
  - cron:  '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Reqs
      run: |
        sudo apt-get install python3-setuptools
    - name: Run
      run: |
        echo "===== Printing commands to be executed ====="
        echo "cd ./google_scholar_crawler"
        echo "pip3 install -r requirements.txt"
        echo "python3 main.py"
        echo "cd ./results"
        echo "git init"
        echo "git config --local user.name \"\${GITHUB_ACTOR}\""
        echo "export remote_repo=\"https://\${GITHUB_ACTOR}:\${{ secrets.GITHUB_TOKEN }}@github.com/\${GITHUB_REPOSITORY}.git\""
        echo "git add *.json"
        echo "git commit -m \"Updated Citation Data\""
        echo "git push \"\${remote_repo}\" HEAD:google-scholar-stats --force"
        echo "===== Checking environment variables ====="
        echo "GITHUB_ACTOR: $GITHUB_ACTOR"
        echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
        echo "GOOGLE_SCHOLAR_ID: $GOOGLE_SCHOLAR_ID"
        echo "GITHUB_TOKEN: ${GITHUB_TOKEN:+[set]}"
        echo "===== Executing commands ====="
        cd ./google_scholar_crawler
        pip3 install -r requirements.txt
        python3 main.py
        cd ./results
        git init
        git config --local user.name "${GITHUB_ACTOR}"
        export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
        git add *.json
        git commit -m "Updated Citation Data"
        git push "${remote_repo}" HEAD:google-scholar-stats --force
      env: 
        GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}